version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/Digital-Bank-0.0.5-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes